language: cpp

before_install:
 - sudo apt-get install libtbb-dev cmake python mpich2 libmpich2-dev

script:
  - python make_kit.py -t --mpi=/usr
  - export CNCROOT=`pwd`/kit.pkg/cnc/current && cd tests && mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-DCNC_REQUIRED_TBB_VERSION=6101" -DRUN_DIST=FALSE .. && make -j 2 && (make test || cat Testing/Temporary/LastTest.log)

compiler:
  - gcc
